"use client";

import { useMemo, useState } from "react";

type View = "dashboard" | "inbox" | "orders" | "customers" | "products" | "suppliers" | "delivery" | "finance" | "automation" | "settings";
type Order = { id:number; orderNo:string; customer:string; user:string; phone:string; address:string; city:string; product:string; qty:number; total:number; cost:number; payment:string; status:string; delivery:string; owner:string; deadline:string; priority:string; notes:string };
type Conversation = { id:number; customer:string; user:string; text:string; unread:boolean; intent:string; status:string; tags:string[] };

const names = ["Salma Ali","Yara Mohamed","Farida Samir","Nadine Adel","Hana Youssef","Dina Fathy","Mariam Nabil","Laila Amin","Jana Tarek","Rana Fouad","Sara Kamal","Nour Emad","Aya Mostafa","Mona Said","Reem Hossam","Mai Gamal","Habiba Sherif","Lina Khaled","Ola Hassan","Nada Ibrahim","Mira Adel","Dalia Omar","Kenzy Wael","Judy Ashraf","Malak Ziad"];
const products = ["Black Crossbody Bag","Summer Linen Dress","Gold Bracelet Set","Gift Box Rose","Oversized Blazer","Silk Scarf","Pearl Hair Clip","Mini Tote Bag","Cotton Lounge Set","Evening Clutch"];
const suppliers = ["Cairo Fashion Supply","Nile Accessories Co.","Alexandria Textile Hub","Istanbul Trend Import","Local Courier Pack"];
const team = ["Nora","Maya","Omar","Lina"];
const statuses = ["New","Needs Info","Confirmed","Awaiting Payment","Paid","Ready for Supplier","Packed","Out for Delivery","Delivered","Returned","Cancelled"];

function initialOrders(): Order[] { return Array.from({length:60},(_,i)=>({id:i+1,orderNo:`LB-2026-${String(i+1).padStart(4,"0")}`,customer:names[i%names.length],user:"@"+names[i%names.length].toLowerCase().replaceAll(" ","."),phone:`+20 10${String(1000000+i*337).padStart(7,"0")}`,address:`${11+i} Garden Street`,city:["Cairo","Giza","Alexandria","Mansoura","Berlin"][i%5],product:products[i%products.length],qty:1+(i%3),total:45+(i%8)*12,cost:18+(i%6)*5,payment:["paid","unpaid","partial","refunded"][i%4],status:statuses[i%statuses.length],delivery:["Not Started","Preparing","With Courier","Delivered","Issue"][i%5],owner:team[i%team.length],deadline:`2026-07-${String(1+(i%20)).padStart(2,"0")}`,priority:i%9===0?"urgent":i%5===0?"high":"normal",notes:i%6===0?"Missing address confirmation":"Instagram DM order"})) }
function initialConversations(): Conversation[] { return Array.from({length:40},(_,i)=>({id:i+1,customer:names[i%names.length],user:"@"+names[i%names.length].toLowerCase().replaceAll(" ","."),text:`I want ${products[i%products.length]}, ${1+i%3} pieces, delivery tomorrow to Garden Street. Phone +20 10${String(2000000+i*91).padStart(7,"0")}`,unread:i%3===0,intent:["new_order","price_question","delivery_question","return_request"][i%4],status:["new","waiting_customer","order_created","paid","issue"][i%5],tags:i%6===0?["urgent","needs phone"]:["instagram"]})) }
function badge(x:string){ const c=x.includes("paid")||x==="Delivered"||x==="Paid"?"ok":x.includes("urgent")||x.includes("Needs")||x.includes("Issue")||x.includes("unpaid")?"warn":""; return <span className={`badge ${c}`}>{x}</span> }
function csv(rows:Order[]){ const cols=["orderNo","customer","user","phone","address","city","product","qty","total","payment","status","delivery","owner","deadline"]; const out=[cols.join(","),...rows.map(r=>cols.map(k=>`"${String(r[k as keyof Order]).replaceAll('"','""')}"`).join(","))].join("\n"); const a=document.createElement("a"); a.href=URL.createObjectURL(new Blob([out],{type:"text/csv"})); a.download="luna-boutique-orders.csv"; a.click(); }
function extract(text:string){ return {product: products.find(p=>text.toLowerCase().includes(p.toLowerCase().split(" ")[0]))||"Black Crossbody Bag", qty:Number(text.match(/(\d+) piece/)?.[1]||1), phone:text.match(/\+20\s?10\d+/)?.[0]||"missing", address:text.includes("Garden")?"Garden Street":"missing", deadline:text.includes("tomorrow")?"tomorrow":"not detected", confidence:88}; }

export default function Page(){
  const [logged,setLogged]=useState(false); const [role,setRole]=useState("owner"); const [view,setView]=useState<View>("dashboard"); const [orders,setOrders]=useState<Order[]>(initialOrders); const [q,setQ]=useState(""); const [conv,setConv]=useState(1); const conversations=useMemo(initialConversations,[]); const current=conversations.find(c=>c.id===conv) || conversations[0]; const ex=extract(current.text); const filtered=orders.filter(o=>(o.orderNo+o.customer+o.user+o.phone+o.status).toLowerCase().includes(q.toLowerCase())); const revenue=orders.filter(o=>o.payment==="paid"||o.payment==="partial").reduce((s,o)=>s+o.total,0); const unpaid=orders.filter(o=>o.payment==="unpaid").reduce((s,o)=>s+o.total,0); const profit=orders.reduce((s,o)=>s+o.total-o.cost*o.qty,0);
  function createFromDm(){ const id=orders.length+1; setOrders([{id,orderNo:`LB-2026-${String(id).padStart(4,"0")}`,customer:current.customer,user:current.user,phone:ex.phone,address:ex.address,city:"Cairo",product:ex.product,qty:ex.qty,total:69,cost:24,payment:"unpaid",status:ex.phone==="missing"?"Needs Info":"Confirmed",delivery:"Not Started",owner:"Maya",deadline:"2026-07-02",priority:"urgent",notes:"Created from Instagram DM"},...orders]); setView("orders"); }
  if(!logged) return <main className="login"><section className="card"><h1>InstaOps CRM</h1><p>Demo login for Luna Boutique. Password is shown for demo purposes.</p><label className="small">Role</label><select value={role} onChange={e=>setRole(e.target.value)}><option>owner</option><option>manager</option><option>staff</option></select><p className="small">owner@luna.demo / demo123</p><button className="btn" onClick={()=>setLogged(true)}>Open demo workspace</button></section></main>;
  return <div className="app"><aside className="sidebar"><div className="brand"><h1>InstaOps CRM</h1><p>Luna Boutique · {role}</p></div><nav className="nav">{["dashboard","inbox","orders","customers","products","suppliers","delivery","finance","automation","settings"].map(v=><button key={v} onClick={()=>setView(v as View)} className={view===v?"active":""}>{v[0].toUpperCase()+v.slice(1)}</button>)}</nav></aside><main className="main"><div className="split" style={{justifyContent:"space-between",marginBottom:20}}><div><h1 style={{margin:0}}>Instagram DM Order OS</h1><p className="small">DMs → order cards → supplier list → shipper list → finance → CRM</p></div><span className="badge ok">Demo connected</span></div>{view==="dashboard"&&<Dashboard orders={orders} revenue={revenue} unpaid={unpaid} profit={profit}/>} {view==="inbox"&&<Inbox conversations={conversations} current={current} conv={conv} setConv={setConv} ex={ex} createFromDm={createFromDm}/>} {view==="orders"&&<Orders orders={filtered} q={q} setQ={setQ} setOrders={setOrders}/>} {view==="customers"&&<Customers orders={orders}/>} {view==="products"&&<Products/>} {view==="suppliers"&&<Suppliers/>} {view==="delivery"&&<Delivery orders={orders}/>} {view==="finance"&&<Finance orders={orders} revenue={revenue} unpaid={unpaid} profit={profit}/>} {view==="automation"&&<Automation/>} {view==="settings"&&<Settings/>}</main></div>
}
function Dashboard({orders,revenue,unpaid,profit}:{orders:Order[];revenue:number;unpaid:number;profit:number}){return <div className="grid"><div className="grid cards"><Card t="Today orders" v={orders.slice(0,11).length}/><Card t="Pending DMs" v="13"/><Card t="Unpaid" v={`€${unpaid}`}/><Card t="Profit estimate" v={`€${profit}`}/></div><div className="grid two"><section className="card"><h2>Urgent workflow</h2><table className="table"><tbody>{orders.filter(o=>o.priority!=="normal").slice(0,8).map(o=><tr key={o.id}><td>{o.orderNo}</td><td>{o.customer}</td><td>{badge(o.status)}</td><td>{o.owner}</td></tr>)}</tbody></table></section><section className="card"><h2>Business pulse</h2><p>Revenue this month: <b>€{revenue}</b></p><p>Orders needing info: <b>{orders.filter(o=>o.status==="Needs Info").length}</b></p><p>Delivery issues: <b>{orders.filter(o=>o.delivery==="Issue").length}</b></p><p>Top product: <b>Black Crossbody Bag</b></p></section></div></div>}
function Card({t,v}:{t:string;v:string|number}){return <section className="card"><h3>{t}</h3><div className="metric">{v}</div></section>}
function Inbox({conversations,current,conv,setConv,ex,createFromDm}:any){return <div className="conversation"><section className="card list">{conversations.map((c:Conversation)=><div key={c.id} onClick={()=>setConv(c.id)} className={`item ${conv===c.id?"active":""}`}><b>{c.customer}</b><p className="small">{c.user} · {c.intent}</p><p>{c.text.slice(0,72)}...</p>{c.unread&&badge("unread")}</div>)}</section><section className="card"><h2>{current.customer}</h2><p className="small">Instagram conversation · {current.user}</p><div className="bubble">{current.text}</div><div className="bubble me">Thanks! I can confirm availability and delivery fee now.</div><div className="split"><button className="btn secondary">Suggest reply</button><button className="btn secondary">Assign to Maya</button></div></section><section className="card"><h2>AI extraction demo</h2>{Object.entries(ex).map(([k,v])=><p key={k}><b>{k}:</b> {String(v)}</p>)}<button className="btn" onClick={createFromDm}>Create order from DM</button><p className="small">Mock extractor only. Production should use official Meta Messaging API webhooks.</p></section></div>}
function Orders({orders,q,setQ,setOrders}:any){return <section className="card"><div className="split"><input className="input" placeholder="Search order/customer/phone/status" value={q} onChange={e=>setQ(e.target.value)}/><button className="btn" onClick={()=>csv(orders)}>Export CSV</button></div><div className="kanban" style={{marginTop:16}}>{["New","Needs Info","Confirmed","Paid"].map(s=><div className="lane" key={s}><b>{s}</b>{orders.filter((o:Order)=>o.status===s).slice(0,5).map((o:Order)=><div className="item" key={o.id}><b>{o.orderNo}</b><p>{o.customer}</p><p className="small">{o.product} · €{o.total}</p></div>)}</div>)}</div><h2>Order table</h2><table className="table"><thead><tr><th>Order</th><th>Customer</th><th>Product</th><th>Payment</th><th>Status</th><th>Owner</th></tr></thead><tbody>{orders.slice(0,25).map((o:Order)=><tr key={o.id}><td>{o.orderNo}</td><td>{o.customer}<br/><span className="small">{o.phone}</span></td><td>{o.product} x{o.qty}</td><td>{badge(o.payment)}</td><td><select value={o.status} onChange={e=>setOrders((all:Order[])=>all.map(x=>x.id===o.id?{...x,status:e.target.value}:x))}>{statuses.map(s=><option key={s}>{s}</option>)}</select></td><td>{o.owner}</td></tr>)}</tbody></table></section>}
function Customers({orders}:{orders:Order[]}){const rows=names.slice(0,25).map(n=>({n,os:orders.filter(o=>o.customer===n)}));return <section className="card"><h2>CRM</h2><div className="grid three">{rows.slice(0,12).map(r=><div className="item" key={r.n}><b>{r.n}</b><p className="small">@{r.n.toLowerCase().replaceAll(" ",".")}</p><p>{r.os.length} orders · €{r.os.reduce((s,o)=>s+o.total,0)}</p>{r.os.length>3&&badge("VIP")}</div>)}</div></section>}
function Products(){return <section className="card"><h2>Products</h2><table className="table"><tbody>{products.map((p,i)=><tr key={p}><td>{p}</td><td>{["Bags","Clothing","Accessories","Gift Boxes"][i%4]}</td><td>€{29+i*6}</td><td>{suppliers[i%suppliers.length]}</td></tr>)}</tbody></table></section>}
function Suppliers(){return <section className="card"><h2>Suppliers</h2>{suppliers.map((s,i)=><div className="item" key={s}><b>{s}</b><p className="small">Lead time {2+i} days · WhatsApp export ready</p></div>)}</section>}
function Delivery({orders}:{orders:Order[]}){const ship=orders.filter(o=>["Paid","Packed","Out for Delivery"].includes(o.status)).slice(0,18);return <section className="card"><div className="split"><h2>Delivery / shipper list</h2><button className="btn" onClick={()=>csv(ship)}>Export shipper CSV</button></div><table className="table"><tbody>{ship.map(o=><tr key={o.id}><td>{o.orderNo}</td><td>{o.customer}</td><td>{o.phone}</td><td>{o.address}, {o.city}</td><td>COD {o.payment==="unpaid"?`€${o.total}`:"€0"}</td></tr>)}</tbody></table></section>}
function Finance({orders,revenue,unpaid,profit}:any){return <div className="grid"><div className="grid cards"><Card t="Revenue" v={`€${revenue}`}/><Card t="Unpaid" v={`€${unpaid}`}/><Card t="Gross profit" v={`€${profit}`}/><Card t="Refunds" v={orders.filter((o:Order)=>o.payment==="refunded").length}/></div><section className="card"><h2>Payment breakdown</h2>{["paid","unpaid","partial","refunded"].map(p=><p key={p}>{badge(p)} {orders.filter((o:Order)=>o.payment===p).length} orders</p>)}</section></div>}
function Automation(){const rules=["If message contains price → suggest price reply","If order has missing phone → mark Needs Info","If deadline is today → mark urgent","If customer has 3+ delivered orders → tag VIP","If unpaid after 24h → create follow-up task","If Ready for Supplier → include in supplier export","If unpaid in delivery export → show COD amount","If return/refund message → tag refund risk"];return <section className="card"><h2>Automation rules</h2>{rules.map(r=><div className="item" key={r}>✅ {r}</div>)}</section>}
function Settings(){return <section className="card"><h2>Instagram connection demo</h2><p>Production integration must use the official Meta Instagram Messaging API and webhooks. This MVP does not scrape Instagram and does not ask for Instagram passwords.</p><p><b>Webhook stubs:</b> GET /api/meta/webhook, POST /api/meta/webhook, POST /api/instagram/send-message</p><p><b>Connection status:</b> demo_connected</p></section>}
